-- MySQL Script generated by MySQL Workbench
-- Wed Oct 18 11:58:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bloodcare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bloodcare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bloodcare` DEFAULT CHARACTER SET utf8 ;
USE `bloodcare` ;

-- -----------------------------------------------------
-- Table `bloodcare`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloodcare`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bloodcare`.`donor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloodcare`.`donor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(16) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `dob` DATE NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `zipcode` INT NOT NULL,
  `street_address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `district` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `contact` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `bloodcare`.`hospital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloodcare`.`hospital` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `regnumber` VARCHAR(45) NOT NULL,
  `name` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `zipcode` INT NOT NULL,
  `street_address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `district` VARCHAR(45) NOT NULL,
  `province` VARCHAR(45) NOT NULL,
  `contact` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `bloodcare`.`donor_bloodtype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloodcare`.`donor_bloodtype` (
  `id` INT NOT NULL,
  `donor_id` INT NOT NULL,
  `bloodtype` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `donor_bloodtype_donor_id`
    FOREIGN KEY (`donor_id`)
    REFERENCES `bloodcare`.`donor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bloodcare`.`bloodcamp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloodcare`.`bloodcamp` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `organizer` VARCHAR(45) NOT NULL,
  `hospital_id` INT NOT NULL,
  `start_datetime` DATETIME NOT NULL,
  `duration` TIMESTAMP NOT NULL,
  `message` VARCHAR(45) NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `bloodcamp_hospital_id`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `bloodcare`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bloodcare`.`bloodcamp_seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloodcare`.`bloodcamp_seats` (
  `bloodcamp_id` INT NOT NULL,
  `max_seats` INT NOT NULL,
  `cur_seats` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`bloodcamp_id`),
  CONSTRAINT `bloodcamp_seats_bloodcamp_id`
    FOREIGN KEY (`bloodcamp_id`)
    REFERENCES `bloodcare`.`bloodcamp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bloodcare`.`bloodcamp_donor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloodcare`.`bloodcamp_donor` (
  `bloodcamp_id` INT NOT NULL,
  `donor_id` INT NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `bloodcamp_donor_bloodcamp_id`
    FOREIGN KEY (`bloodcamp_id`)
    REFERENCES `bloodcare`.`bloodcamp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bloodcamp_donor_donor_id`
    FOREIGN KEY (`donor_id`)
    REFERENCES `bloodcare`.`donor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bloodcare`.`appointmentslot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloodcare`.`appointmentslot` (
  `id` INT NOT NULL,
  `hospital_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `time_slot` TIME NOT NULL,
  `duration` TIME NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `appointmentslot_hospital_id`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `bloodcare`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bloodcare`.`donor_appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloodcare`.`donor_appointment` (
  `id` INT NOT NULL,
  `donor_id` INT NOT NULL,
  `appointmentslot_id` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `donor_appointment_donor_id`
    FOREIGN KEY (`donor_id`)
    REFERENCES `bloodcare`.`donor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `donor_appointment_appointmentslot_id`
    FOREIGN KEY (`appointmentslot_id`)
    REFERENCES `bloodcare`.`appointmentslot` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bloodcare`.`donor_donation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloodcare`.`donor_donation` (
  `id` INT NOT NULL,
  `donor_id` INT NOT NULL,
  `donation_type` VARCHAR(45) NOT NULL,
  `hospital_id` INT NULL,
  `bloodcamp_id` INT NULL,
  `report` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `donor_id`
    FOREIGN KEY (`donor_id`)
    REFERENCES `bloodcare`.`donor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `donor_donation_hospital_id`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `bloodcare`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `donor_donation_bloodcamp_id`
    FOREIGN KEY (`bloodcamp_id`)
    REFERENCES `bloodcare`.`bloodcamp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bloodcare`.`hospital_bloodrequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bloodcare`.`hospital_bloodrequest` (
  `id` INT NOT NULL,
  `hospital_id` INT NOT NULL,
  `bloodtype` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `qty` INT NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `hospital_bloodrequest_hospital_id`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `bloodcare`.`hospital` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `donor` AUTO_INCREMENT=1000;
ALTER TABLE `hospital` AUTO_INCREMENT=100;
ALTER TABLE `admin` AUTO_INCREMENT=10;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
